---
- name: Create string
  ansible.builtin.set_fact:
    port_string: "{{ entrypoint.port }}{{ ':' }}{{ entrypoint.port }}/{{ entrypoint.protocol }}"

- name: Create port mapping for traefik docker configuration
  ansible.builtin.set_fact:
    docker_traefik_ports: "{{ docker_traefik_ports + [port_string] }}"
