---
- name: Create string
  ansible.builtin.set_fact:
    port_string: "{{ exposed_port.port }}{{ ':' }}{{ exposed_port.port }}/{{ exposed_port.protocol }}"

- name: Create port mapping for traefik docker configuration
  ansible.builtin.set_fact:
    traefik_ports: "{{ traefik_ports + [port_string] }}"
