---
- name: Converge
  hosts: all
  become: true

  vars:
    docker_install_traefik: true
    docker_install_watchtower: true
    docker_install_portainer: true
    docker_install_portainer_agent: true

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Wait for systemd to complete initialization.
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1
    - name: Run docker install role
      ansible.builtin.include_role:
        name: geerlingguy.docker

    - name: Run pip install role
      ansible.builtin.include_role:
        name: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker

  roles:
    - role: fw_oss.docker_stack
